#######
# The jenkins CLI command. Note the '>-' to strip the \n from the end of
# the command.
jenkins_cli_cmd: >-
  /usr/bin/java -jar /home/vagrant/jenkins-cli.jar
  -s http://localhost:8080
  -i /var/lib/jenkins/.ssh/id_rsa

#######
# Use this URL when waiting for the service to retun a '200 OK'.
jenkins_login_url: http://localhost:8080/login


#######
# All the Jenkins Plugins to install using the CLI
jenkins_plugins:
  - build-timeout
  - build-pipeline-plugin
  - timestamper
  - ws-cleanup
  - gradle
  - git
  - blueocean
  - ssh-slaves
  - junit
