---

#######
# Install Jenkins from the Jenkins debian repo
- name: Add Jenkins repo to APT
  lineinfile:
    dest: /etc/apt/sources.list.d/jenkins.list
    create: yes
    line: deb http://pkg.jenkins.io/debian-stable binary/

- name: Add Jenkins repo key to APT
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io.key
    state: present

- name: Install Jenkins2
  apt:
    name: jenkins
    state: latest
    update_cache: yes

#####
# give the jenkins user a pwd and login shell
- name: Set jenkins shell
  user: name=jenkins shell=/bin/bash

- name: Set jenkins pwd
  shell: echo "jenkins:jenkins" | chpasswd

- name: No Jenkins Wizard Thank You
  lineinfile:
    dest: /etc/default/jenkins
    regexp: ^JENKINS_JAVA_OPTIONS
    line: JAVA_OPTIONS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"

#####
# To avoid having to enter the gui and set up jenkins, copy all the
# configuration into the running instance. Includes the jenkins user's ssh key
# for authorization when running the CLI
- name: Copy Jenkins config
  copy:
    src: /vagrant/files/jenkins_home/
    dest: /var/lib/jenkins
    owner: jenkins
    group: jenkins
    mode: 0755

#######
# ssh is, of course, very picky about file permissions
- name: Public key perms
  file:
    path: /var/lib/jenkins/.ssh/id_rsa.pub
    owner: jenkins
    group: jenkins
    mode: 644

- name: Private key perms
  file:
    path: /var/lib/jenkins/.ssh/id_rsa.pub
    owner: jenkins
    group: jenkins
    mode: 600

#######
# Restart the service and keep it running
- name: Start and enable Jenkins
  service:
    name: jenkins
    state: restarted
    enabled: yes

#######
# Pause the playbook until jenkins is running by polling the Jenkins
# webservice.
- name: Wait for Jenkins to start
  command: curl --head --silent {{ jenkins_login_url }}
  register: result
  until: result.stdout.find("200 OK") != -1
  retries: 10
  delay: 5
  changed_when: false

#####
# Install plugins using the Jenkins CLI
- name: Download Jenkins CLI
  get_url:
    url: http://localhost:8080/jnlpJars/jenkins-cli.jar
    dest: /home/vagrant/jenkins-cli.jar
    mode: 0755
    timeout: 30

- name: Install Plugins
  shell: "{{ jenkins_cli_cmd }} install-plugin {{ item }} -deploy"
  with_items: "{{ jenkins_plugins }}"

#######
# The plugins require a restart.
- name: Final Restart
  service:
    name: jenkins
    state: restarted
